name: flutter_projem
description: Cocktails.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  chopper: ^4.0.1
  flutter_dotenv: ^5.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  chopper_generator: ^4.0.1
  json_serializable: ^6.1.3
  build_runner: ^2.0.5 
  mockito: ^5.0.17
  bloc_test: ^9.0.2


flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/kraken.png"

assets:
  - .env